spring.application.name=API

## Database Properties
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/demo_sales?useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = validate

#JWT
app.jwt.secret=${SECRET_KEY:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}
app.jwt.expiration-seconds=3600
app.jwt.issuer=api
