spring.application.name=API

## Database Properties
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/demo_sales?useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
